export const FETCH_POSTS = 'FETCH_POSTS';
export const NEW_POST = 'NEW_POST';
export const PINCODE_DETAILS='PINCODE_DETAILS'
export const SOURCE_COORDINATES='SOURCE_COORDINATES'
export const VISCINITY_DISTRICT_APPOINTMENTS='VISCINITY_DISTRICT_APPOINTMENTS'
export const CURRENCT_VISCINITY_DISTRICTS='CURRENCT_VISCINITY_DISTRICTS'
export const AVAILAIBLE_APPOINTMENTS='AVAILAIBLE_APPOINTMENTS'
